# Generated by Django 2.2.6 on 2019-11-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='user',
            name='family',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
