# Generated by Django 2.2.6 on 2019-11-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
