# Generated by Django 2.2.6 on 2019-11-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0010_auto_20191103_1638'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
